# Global configuration (optional)
global:
  imagePullPolicy: IfNotPresent
  replicas: 1

ingress:
  name: campi-ingress
  className: nginx  


# Frontend service
frontend:
  replicas: 1
  image:
    repository: hjaiejhoussem
    name: campi-frontend
    tag: "1.0.19"
  servicePort: 4001
  containerPort: 80

# Backend service
backend:
  replicas: 2
  image:
    repository: hjaiejhoussem
    name: campi-api
  servicePort: 4000
  containerPort: 3000
  envVariables:
  - MONGODB_HOST
  - MONGODB_USER
  - MONGODB_PASSWORD
  - MONGODB_PORT
  - MONGODB_DATABASE
  - MONGODB_AUTH_SOURCE

# Database service
database:
  replicas: 1
  image:
      name: mongo
      tag: "6-jammy"
  servicePort: 27017
  containerPort: 27017
  envVariables:
  - MONGO_INITDB_ROOT_USERNAME
  - MONGO_INITDB_ROOT_PASSWORD

# vault integration
vault:
  server: "http://vault.vault.svc.cluster.local:8200"
  path: "kv" 
  version: "v2"
  secretName: "vault-token-secret"
  secretKey: "token"
  targetSecret: "mongo-db-secret"



