apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
spec:
  selector:
    {{- include "backend.labels" . | indent 4 }}
  ports:
  - port: {{ .Values.backend.servicePort }}
    targetPort: {{ .Values.backend.containerPort }}