apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db-deployment
  labels:
    {{- include "database.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      {{- include "database.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "database.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}-db-container 
        image: "{{ .Values.database.image.name }}:{{ .Values.database.image.tag }}"
        ports:
        - containerPort: {{ .Values.database.containerPort }}
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.vault.targetSecret }}
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.vault.targetSecret }}
                key: MONGO_INITDB_ROOT_PASSWORD
