apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-service
spec:
  selector:
    {{- include "database.labels" . | indent 4}}
  ports:
  - port: {{ .Values.database.servicePort }}
    targetPort: {{ .Values.database.containerPort }}