apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Release.Name }}-vault-backend
    kind: SecretStore
  target:
    name: {{ .Values.vault.targetSecret }}
  data:
  - secretKey: MONGODB_HOST
    remoteRef:
      key: kv/campi
      property: MONGODB_HOST
  - secretKey: MONGODB_USER
    remoteRef:
      key: kv/campi
      property: MONGODB_USER
  - secretKey: MONGODB_PASSWORD
    remoteRef:
      key: kv/campi
      property: MONGODB_PASSWORD
  - secretKey: MONGODB_PORT
    remoteRef:
      key: kv/campi
      property: MONGODB_PORT
  - secretKey: MONGODB_DATABASE
    remoteRef:
      key: kv/campi
      property: MONGODB_DATABASE
  - secretKey: MONGODB_AUTH_SOURCE
    remoteRef:
      key: kv/campi
      property: MONGODB_AUTH_SOURCE
  - secretKey: MONGO_INITDB_ROOT_USERNAME
    remoteRef:
      key: kv/campi
      property: MONGO_INITDB_ROOT_USERNAME
  - secretKey: MONGO_INITDB_ROOT_PASSWORD
    remoteRef:
      key: kv/campi
      property: MONGO_INITDB_ROOT_PASSWORD