apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-vault-backend
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.path }}
      version: {{ .Values.vault.version }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.secretName }}
          key: {{ .Values.vault.secretKey }}