apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Release.Name }}-vault-backend
    kind: SecretStore
  target:
    name: {{ .Values.vault.targetSecret }}
  data:
  {{- include "back-es.envVars" . | indent 2 }}
  {{- include "bd-es.envVars" . | indent 2 }}